name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    name: Lint, Type Check & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit pytest

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest
